FROM fedora:26
LABEL maintainer="Claudio Ramirez <pub.claudio@gmail.com>"

ENV LANG='en_US.UTF-8' \
    pkgs='git perl-core wget' \
    pkggroup='Development Tools'

RUN set -xv ; \
    dnf -q -y upgrade && \
    dnf -q install -y ${pkgs} && \
    dnf -q groupinstall -y "${pkggroup}" && \
    dnf -q clean all

COPY compile.sh /

ENTRYPOINT [ "/compile.sh" ]
