FROM nxadm/ubuntu-i386:16.04
LABEL maintainer="Claudio Ramirez <pub.claudio@gmail.com>"

ENV LANG='C.UTF-8' \
    DEBIAN_FRONTEND='noninteractive' \
    pkgs='build-essential git wget'

RUN set -xv ; \
    apt-get -qq update && \
    apt-get -qq dist-upgrade -y && \
    apt-get -qq install -y ${pkgs} && \
    apt-get -qq clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY compile.sh /

ENTRYPOINT [ "bash", "/compile.sh" ]
