FROM opensuse:42.3
LABEL maintainer="Claudio Ramirez <pub.claudio@gmail.com>"
ENV LANG='en_US.UTF-8' \
    pkgs='git gcc lsb5-core make wget'

RUN set -xv ; \
    zypper refresh && \
    zypper update -y && \
    zypper install --replacefiles -y ${pkgs}

COPY compile.sh /

ENTRYPOINT [ "bash", "/compile.sh" ]
