FROM alpine:3.6
LABEL maintainer="Claudio Ramirez <pub.claudio@gmail.com>"

ENV LANG='C.UTF-8'
ENV TZ='Europe/Brussels'
ENV pkgs='build-base ca-certificates git libc-dev linux-headers openssl perl perl-utils wget zlib gzip tar git'

RUN set -xv ; \
apk update && apk upgrade && \
apk add --no-cache ${pkgs} && \
update-ca-certificates && \
cp /usr/share/zoneinfo/${TZ} /etc/localtime && \
echo "${TZ}" > /etc/timezone && \
rm -rf /tmp/* /var/tmp/* /rakudo*

COPY pkg_rakudo.pl /

ENTRYPOINT [ "/pkg_rakudo.pl" ]
